# Generated by Django 5.1.1 on 2024-09-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('date_birth', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('sex', models.CharField(max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
